companies:
  - name: "Flutter Entertainment"
    ticker_us: "FLUT"
    country: "UK/US"
    category: "operator"
    allowed_domains: ["flutter.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.flutter.com/investors/regulatory-news"
      - type: "page"
        url: "https://www.flutter.com/investors/results-reports-and-presentations/year/2025/"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Flutter%20Entertainment"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Flutter%20Entertainment%22"

  - name: "Entain plc"
    country: "UK"
    category: "operator"
    allowed_domains: ["entaingroup.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.entaingroup.com/investor-relations/regulatory-news/"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Entain"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/Entain"

  - name: "Evoke plc (ex-888)"
    country: "UK"
    category: "operator"
    allowed_domains: ["evokeplc.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.evokeplc.com/investors/regulatory-news/"
      - type: "page"
        url: "https://www.evokeplc.com/investors/results-reports-and-presentations/"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Evoke%20plc%20OR%20888"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22888%22%20OR%20%22Evoke%20plc%22"

  - name: "DraftKings"
    ticker_us: "DKNG"
    country: "US"
    category: "operator"
    allowed_domains: ["draftkings.gcs-web.com", "draftkings.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "rss_page"
        url: "https://draftkings.gcs-web.com/shareholder-services/rss-feeds/"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=DraftKings"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/DraftKings"

  - name: "MGM Resorts"
    ticker_us: "MGM"
    country: "US"
    category: "operator"
    allowed_domains: ["investors.mgmresorts.com", "mgmresorts.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "rss_page"
        url: "https://investors.mgmresorts.com/rss/"
      - type: "page"
        url: "https://investors.mgmresorts.com/investors/news-releases/default.aspx"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=MGM%20Resorts"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22MGM%20Resorts%22"

  - name: "Caesars Entertainment"
    ticker_us: "CZR"
    country: "US"
    category: "operator"
    allowed_domains: ["investor.caesars.com", "caesars.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://investor.caesars.com/press-releases"
      - type: "page"
        url: "https://investor.caesars.com/events/"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Caesars%20Entertainment"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Caesars%20Entertainment%22"

  - name: "PENN Entertainment"
    ticker_us: "PENN"
    country: "US"
    category: "operator"
    allowed_domains: ["pennnationalgaming.gcs-web.com", "pennentertainment.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "rss_page"
        url: "https://pennnationalgaming.gcs-web.com/rss-feeds"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=PENN%20Entertainment"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22PENN%20Entertainment%22"

  - name: "Super Group (Betway / Spin)"
    ticker_us: "SGHC"
    country: "Global/US"
    category: "operator"
    allowed_domains: ["investors.supergroup.com", "globenewswire.com", "businesswire.com"]
    watchers:
      - type: "page"
        url: "https://investors.supergroup.com/news-and-events/press-releases/default.aspx"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Super%20Group%22"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=%22Super%20Group%22%20OR%20Betway%20OR%20Spin"

  - name: "Betsson AB"
    country: "Sweden"
    category: "operator"
    allowed_domains: ["betssonab.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.betssonab.com/newsroom/press-releases"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Betsson%20AB%22%20OR%20Betsson"

  - name: "Evolution AB"
    country: "Sweden"
    category: "supplier"
    allowed_domains: ["evolution.com", "globenewswire.com", "businesswire.com"]
    watchers:
      - type: "page"
        url: "https://www.evolution.com/investors/press-releases/"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Evolution%20AB%22%20OR%20%22Evolution%20Gaming%22"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=%22Evolution%20AB%22%20OR%20%22Evolution%20Gaming%22"

  - name: "Light & Wonder (LNW)"
    ticker_us: "LNW"
    country: "US/Australia"
    category: "supplier"
    allowed_domains: ["lnw.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.lnw.com/investors"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=%22Light%20%26%20Wonder%22"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Light%20%26%20Wonder%22%20OR%20LNW"

  - name: "Playtech plc"
    country: "UK"
    category: "supplier"
    allowed_domains: ["investors.playtech.com", "playtech.com", "businesswire.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.investors.playtech.com/regulatory-news"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Playtech"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/Playtech"

  - name: "Kambi Group"
    country: "Sweden/Malta"
    category: "supplier"
    allowed_domains: ["kambi.com", "globenewswire.com"]
    watchers:
      - type: "page"
        url: "https://www.kambi.com/investors/press-releases/"
      - type: "page"
        url: "https://www.kambi.com/investors/financial-reports-and-presentations/"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/Kambi"

  - name: "Sportradar"
    ticker_us: "SRAD"
    country: "Switzerland/US"
    category: "data"
    allowed_domains: ["globenewswire.com", "sportradar.com", "businesswire.com"]
    watchers:
      - type: "rss"
        url: "https://rss.globenewswire.com/rssfeed/organization/bUQ4MtcTvBAjR_cda0el8g%3D%3D"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Sportradar%20OR%20SRAD"

  - name: "Genius Sports"
    ticker_us: "GENI"
    country: "UK/US"
    category: "data"
    allowed_domains: ["investors.geniussports.com", "geniussports.com", "globenewswire.com", "businesswire.com"]
    watchers:
      - type: "page"
        url: "https://investors.geniussports.com/news/default.aspx"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Genius%20Sports%22"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=%22Genius%20Sports%22%20OR%20GENI"

  # Sector-wide wires (focused)
  - name: "Sector news wires"
    category: "aggregator"
    allowed_domains: ["businesswire.com", "globenewswire.com"]
    watchers:
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=igaming%20OR%20%22sports%20betting%22%20OR%20casino"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/igaming%20OR%20%22sports%20betting%22%20OR%20casino"
