companies:
  - name: Flutter Entertainment
    ticker_us: FLUT
    country: UK / US
    category: operator
    allowed_domains:
      - flutter.com
    watchers:
      - type: page
        url: https://www.flutter.com/investors/regulatory-news
      - type: page
        url: https://www.flutter.com/investors/results-reports-and-presentations/year/2025/

  - name: Entain plc
    country: UK
    category: operator
    allowed_domains:
      - entaingroup.com
    watchers:
      - type: page
        url: https://www.entaingroup.com/investor-relations/regulatory-news/

  - name: Evoke plc (ex-888)
    country: UK
    category: operator
    allowed_domains:
      - evokeplc.com
    watchers:
      - type: page
        url: https://www.evokeplc.com/investors/regulatory-news/
      - type: page
        url: https://www.evokeplc.com/investors/results-reports-and-presentations/

  - name: DraftKings
    ticker_us: DKNG
    country: US
    category: operator
    allowed_domains:
      - draftkings.gcs-web.com
      - businesswire.com
    watchers:
      - type: rss_page
        url: https://draftkings.gcs-web.com/shareholder-services/rss-feeds/
      - type: wire
        url: https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=DraftKings

  - name: MGM Resorts
    ticker_us: MGM
    country: US
    category: operator
    allowed_domains:
      - investors.mgmresorts.com
      - mgmresorts.com
      - businesswire.com
    watchers:
      - type: rss_page
        url: https://investors.mgmresorts.com/rss/
      - type: page
        url: https://investors.mgmresorts.com/investors/news-releases/default.aspx
      - type: wire
        url: https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=MGM%20Resorts

  - name: Caesars Entertainment
    ticker_us: CZR
    country: US
    category: operator
    allowed_domains:
      - investor.caesars.com
      - caesars.com
      - businesswire.com
    watchers:
      - type: page
        url: https://investor.caesars.com/press-releases
        allowed_domains: [ "investor.caesars.com", "caesars.com" ]
        follow_detail: true
      - type: page
        url: https://investor.caesars.com/events/
        allowed_domains: [ "investor.caesars.com", "caesars.com" ]
        follow_detail: true
      - type: wire
        url: https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=Caesars%20Entertainment

  - name: PENN Entertainment
    ticker_us: PENN
    country: US
    category: operator
    allowed_domains:
      - pennnationalgaming.gcs-web.com
      - businesswire.com
    watchers:
      - type: rss_page
        url: https://pennnationalgaming.gcs-web.com/rss-feeds
      - type: wire
        url: https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=PENN%20Entertainment

  - name: Super Group (Betway / Spin)
    ticker_us: SGHC
    country: Global / US
    category: operator
    allowed_domains:
      - investors.supergroup.com
      - globenewswire.com
    watchers:
      - type: page
        url: https://investors.supergroup.com/news-and-events/press-releases/default.aspx
      - type: wire
        url: https://www.globenewswire.com/Search/NewsSearch?keyword=Super%20Group

  - name: Betsson AB
    country: Sweden
    category: operator
    allowed_domains:
      - betssonab.com
    watchers:
      - type: page
        url: https://www.betssonab.com/newsroom/press-releases

  - name: Evolution AB
    country: Sweden
    category: supplier
    allowed_domains:
      - evolution.com
    watchers:
      - type: page
        url: https://www.evolution.com/investors/press-releases/

  - name: Light & Wonder (LNW)
    ticker_us: LNW
    country: US / Australia
    category: supplier
    allowed_domains:
      - lnw.com
      - businesswire.com
    watchers:
      - type: page
        url: https://www.lnw.com/investors
      - type: wire
        url: https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=%22Light%20%26%20Wonder%22

  - name: Playtech plc
    country: UK
    category: supplier
    allowed_domains:
      - investors.playtech.com
      - playtech.com
    watchers:
      - type: page
        url: https://www.investors.playtech.com/regulatory-news

  - name: Kambi Group
    country: Sweden / Malta
    category: supplier
    allowed_domains:
      - kambi.com
    watchers:
      - type: page
        url: https://www.kambi.com/investors/press-releases/
      - type: page
        url: https://www.kambi.com/investors/financial-reports-and-presentations/

  - name: Sportradar
    ticker_us: SRAD
    country: Switzerland / US
    category: data
    allowed_domains:
      - globenewswire.com
      - sportradar.com
    watchers:
      - type: rss
        url: https://rss.globenewswire.com/rssfeed/organization/bUQ4MtcTvBAjR_cda0el8g%3D%3D

  - name: Genius Sports
    ticker_us: GENI
    country: UK / US
    category: data
    allowed_domains:
      - investors.geniussports.com
      - globenewswire.com
    watchers:
      - type: page
        url: https://investors.geniussports.com/news/default.aspx
        allowed_domains: [ "investors.geniussports.com", "geniussports.com", "businesswire.com", "globenewswire.com" ]
        follow_detail: true
      - type: wire
        url: https://www.globenewswire.com/Search/NewsSearch?keyword=Genius%20Sports

  - name: Sector news wires
    category: aggregator
    allowed_domains:
      - businesswire.com
      - globenewswire.com
    watchers:
      - type: wire
        url: https://www.businesswire.com/newsroom?keywords=ENTIRE_RELEASE%3Atrue%3Aigaming
      - type: wire
        url: https://www.globenewswire.com/en/search/keyword/igaming,igaming%252520quarter
