companies:
  - name: "Flutter Entertainment"
    ticker_us: "FLUT"
    country: "UK/US"
    category: "operator"
    allowed_domains:
      - "flutter.com"
      - "businesswire.com"
      - "globenewswire.com"
      - "prnewswire.com"
      - "newsfilecorp.com"
      - "newsdirect.com"
    watchers:
      - type: "page"
        url: "https://www.flutter.com/investors/regulatory-news"
      - type: "page"
        url: "https://www.flutter.com/investors/results-reports-and-presentations/year/2025/"
      - type: "gnews"
        query: "(\"Flutter Entertainment\" OR FLUT) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR \"trading update\" OR guidance) (site:businesswire.com OR site:globenewswire.com OR site:prnewswire.com OR site:newsfilecorp.com OR site:newsdirect.com)"
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=Flutter%20Entertainment"

  - name: "Entain plc"
    country: "UK"
    category: "operator"
    allowed_domains:
      - "entaingroup.com"
      - "businesswire.com"
      - "globenewswire.com"
      - "prnewswire.com"
    watchers:
      - type: "page"
        url: "https://www.entaingroup.com/investor-relations/regulatory-news/"
      - type: "gnews"
        query: "(\"Entain\" OR \"Entain plc\") (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR \"trading update\" OR guidance) (site:businesswire.com OR site:globenewswire.com OR site:prnewswire.com)"

  - name: "Evoke plc (ex-888)"
    country: "UK"
    category: "operator"
    allowed_domains:
      - "evokeplc.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://www.evokeplc.com/investors/regulatory-news/"
      - type: "page"
        url: "https://www.evokeplc.com/investors/results-reports-and-presentations/"
      - type: "gnews"
        query: "(\"Evoke plc\" OR 888) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR \"trading update\" OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "DraftKings"
    ticker_us: "DKNG"
    country: "US"
    category: "operator"
    allowed_domains:
      - "draftkings.gcs-web.com"
      - "draftkings.com"
      - "businesswire.com"
      - "globenewswire.com"
      - "prnewswire.com"
    watchers:
      - type: "rss_page"
        url: "https://draftkings.gcs-web.com/shareholder-services/rss-feeds/"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=DraftKings"
      - type: "gnews"
        query: "(DraftKings OR DKNG) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:businesswire.com OR site:globenewswire.com OR site:prnewswire.com)"

  - name: "MGM Resorts"
    ticker_us: "MGM"
    country: "US"
    category: "operator"
    allowed_domains:
      - "investors.mgmresorts.com"
      - "mgmresorts.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "rss_page"
        url: "https://investors.mgmresorts.com/rss/"
      - type: "page"
        url: "https://investors.mgmresorts.com/investors/news-releases/default.aspx"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=MGM%20Resorts"
      - type: "gnews"
        query: "(\"MGM Resorts\") (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "Caesars Entertainment"
    ticker_us: "CZR"
    country: "US"
    category: "operator"
    allowed_domains:
      - "investor.caesars.com"
      - "caesars.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://investor.caesars.com/press-releases"
      - type: "page"
        url: "https://investor.caesars.com/events/"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=Caesars%20Entertainment"
      - type: "gnews"
        query: "(\"Caesars Entertainment\" OR CZR) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "PENN Entertainment"
    ticker_us: "PENN"
    country: "US"
    category: "operator"
    allowed_domains:
      - "pennnationalgaming.gcs-web.com"
      - "pennentertainment.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "rss_page"
        url: "https://pennnationalgaming.gcs-web.com/rss-feeds"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=PENN%20Entertainment"
      - type: "gnews"
        query: "(\"PENN Entertainment\" OR PENN) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "Super Group (Betway / Spin)"
    ticker_us: "SGHC"
    country: "Global/US"
    category: "operator"
    allowed_domains:
      - "investors.supergroup.com"
      - "globenewswire.com"
      - "businesswire.com"
    watchers:
      - type: "page"
        url: "https://investors.supergroup.com/news-and-events/press-releases/default.aspx"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Super%20Group%22"
      - type: "gnews"
        query: "(\"Super Group\" Betway Spin) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com OR site:businesswire.com)"

  - name: "Betsson AB"
    country: "Sweden"
    category: "operator"
    allowed_domains:
      - "betssonab.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://www.betssonab.com/newsroom/press-releases"
      - type: "gnews"
        query: "(\"Betsson AB\" OR Betsson) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com)"

  - name: "Evolution AB"
    country: "Sweden"
    category: "supplier"
    allowed_domains:
      - "evolution.com"
      - "globenewswire.com"
      - "businesswire.com"
    watchers:
      - type: "page"
        url: "https://www.evolution.com/investors/press-releases/"
      - type: "gnews"
        query: "(\"Evolution AB\" OR \"Evolution Gaming\") (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com OR site:businesswire.com)"

  - name: "Light & Wonder (LNW)"
    ticker_us: "LNW"
    country: "US/Australia"
    category: "supplier"
    allowed_domains:
      - "lnw.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://www.lnw.com/investors"
      - type: "wire"
        url: "https://www.businesswire.com/portal/site/home/search/?searchType=news&searchTerm=%22Light%20%26%20Wonder%22"
      - type: "gnews"
        query: "(\"Light & Wonder\" OR LNW) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "Playtech plc"
    country: "UK"
    category: "supplier"
    allowed_domains:
      - "investors.playtech.com"
      - "playtech.com"
      - "businesswire.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://www.investors.playtech.com/regulatory-news"
      - type: "gnews"
        query: "(Playtech) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR \"trading update\" OR guidance) (site:businesswire.com OR site:globenewswire.com)"

  - name: "Kambi Group"
    country: "Sweden/Malta"
    category: "supplier"
    allowed_domains:
      - "kambi.com"
      - "globenewswire.com"
    watchers:
      - type: "page"
        url: "https://www.kambi.com/investors/press-releases/"
      - type: "page"
        url: "https://www.kambi.com/investors/financial-reports-and-presentations/"
      - type: "gnews"
        query: "(\"Kambi Group\" OR Kambi) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com)"

  - name: "Sportradar"
    ticker_us: "SRAD"
    country: "Switzerland/US"
    category: "data"
    allowed_domains:
      - "globenewswire.com"
      - "sportradar.com"
      - "businesswire.com"
    watchers:
      - type: "rss"
        url: "https://rss.globenewswire.com/rssfeed/organization/bUQ4MtcTvBAjR_cda0el8g%3D%3D"
      - type: "gnews"
        query: "(Sportradar OR SRAD) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com OR site:businesswire.com)"

  - name: "Genius Sports"
    ticker_us: "GENI"
    country: "UK/US"
    category: "data"
    allowed_domains:
      - "investors.geniussports.com"
      - "geniussports.com"
      - "globenewswire.com"
      - "businesswire.com"
    watchers:
      - type: "page"
        url: "https://investors.geniussports.com/news/default.aspx"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/%22Genius%20Sports%22"
      - type: "gnews"
        query: "(\"Genius Sports\" OR GENI) (Q1 OR Q2 OR Q3 OR Q4 OR earnings OR results OR guidance) (site:globenewswire.com OR site:businesswire.com)"

  - name: "Sector news wires"
    category: "aggregator"
    allowed_domains:
      - "businesswire.com"
      - "globenewswire.com"
      - "prnewswire.com"
      - "newsfilecorp.com"
      - "newsdirect.com"
    watchers:
      - type: "wire"
        url: "https://www.businesswire.com/newsroom?keywords=igaming%20OR%20%22sports%20betting%22%20OR%20casino"
      - type: "wire"
        url: "https://www.globenewswire.com/en/search/keyword/igaming%20OR%20%22sports%20betting%22%20OR%20casino"
