name: igwatch

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env from secrets
        run: |
          cat > .env <<'EOF'
          GRAPH_TENANT_ID=${{ secrets.GRAPH_TENANT_ID }}
          GRAPH_CLIENT_ID=${{ secrets.GRAPH_CLIENT_ID }}
          GRAPH_CLIENT_SECRET=${{ secrets.GRAPH_CLIENT_SECRET }}
          MAIL_FROM=${{ secrets.MAIL_FROM }}
          MAIL_TO=${{ secrets.MAIL_TO }}
          SEC_USER_AGENT=NEXT.io Earnings Watcher (contact: ${{ secrets.MAIL_FROM }})
          DRY_RUN=true
          POLL_SECONDS=60
          EOF

      - name: Run watcher once (idempotent)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          . .venv/bin/activate
          python -m app.main
