name: igwatch

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Log instead of sending emails"
        type: choice
        options: [ "true", "false" ]
        default: "true"
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore state DB
        uses: actions/cache@v4
        with:
          path: seen.db
          key: igwatch-seen-db-v1

      # Decide timeouts and poll speed per event type
      - name: Choose runtime params
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RUN_TIMEOUT=180" >> $GITHUB_ENV          # 3 minutes for manual debug
            echo "POLL_SECONDS_OVERRIDE=20" >> $GITHUB_ENV # faster first poll
          else
            echo "RUN_TIMEOUT=50" >> $GITHUB_ENV           # short for scheduled runs (cost control)
            echo "POLL_SECONDS_OVERRIDE=60" >> $GITHUB_ENV
          fi

      # .github/workflows/igwatch.yml  → in "Create .env for this run"
- name: Create .env for this run
  run: |
    {
      echo "MAIL_TRANSPORT=smtp"
      echo "MAIL_FROM=stuatnext@gmail.com"
      echo "MAIL_TO=stuatnext@gmail.com"
      echo "SEC_USER_AGENT=NEXT.io Earnings Watcher (contact: stuatnext@gmail.com)"

      # Gmail SMTP
      echo "SMTP_HOST=smtp.gmail.com"
      echo "SMTP_PORT=587"
      echo "SMTP_USER=stuatnext@gmail.com"
      echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"

      # Runtime knobs
      echo "POLL_SECONDS=20"
      echo "DRY_RUN=false"       # ← change this line
    } > .env

      - name: Run watcher (bounded)
        run: |
          if command -v timeout >/dev/null 2>&1; then
            timeout ${RUN_TIMEOUT}s python -m app.main
          else
            python -m app.main
          fi

      - name: Persist logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: igwatch-logs
          path: "**/*.log"
          if-no-files-found: ignore
